# -*- coding: utf-8 -*-

import pylrc #https://github.com/doakey3/pylrc
import glob
import os
import codecs

os.chdir("C:\\Users\\Ray\\Documents\\GitHub\\XBN\\LRC")
for file in glob.glob("*.lrc"):
    filename = file[0:7]

    lrc_file = open(file)
    lrc_lines = lrc_file.readlines()
    lrc_parse = ''.join(lrc_lines)
    lrc_file.close()

    cue = codecs.open(filename + '.cue','w','utf-8')
    cue.write(u'\uFEFF') # we're using UTF-8-BOM for compatibility with foobar2000

    lrc = pylrc.parse(lrc_parse)
    print(lrc.artist, '-' ,lrc.title)
    trackno = 1

    cue.write('REM GENRE Podcast\n')
    cue.write('REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."\n')
    cue.write('TITLE "' + lrc.title + '"\n')
    cue.write('PERFORMER "' + lrc.artist + '"\n')
    cue.write('FILE "' + filename + '.mp3' + '" MP3\n')
    for line in lrc_lines[3:]:
        tracktime = line[line.find("[")+1:line.find("]")].replace('.', ':')
        cue.write('  TRACK ' + str(trackno).zfill(2) + ' AUDIO\n')
        cue.write('    TITLE "' + line.split(']',1)[1].rstrip('\n') + '"\n')
        cue.write('    INDEX 01 ' + tracktime + '\n')
        trackno += 1
    cue.close()
