#!/bin/bash

#!!! IN DEVELOPMENT RIGHT NOW !!!

# Generate cue files using @xanamp tweets. version 1
# CHANGE PATHS BEFORE USING THIS SCRIPT.
# supply tweets.csv withe following format:
# 2018-02-18-03:13:53\FurCast - News
# 2018-02-18-03:07:46\GoldFish, Julia Church - Heart Shaped Box (Original Mix)

# Cue file reference.
# REM GENRE Podcast
# REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
# TITLE "fnt-193"
# FILE "fnt-193.mp3" WAVE
#   TRACK 01 AUDIO
#     TITLE "Intro"
#     INDEX 01 00:00:00
#   TRACK 02 AUDIO
#     TITLE "Unknown Artist - Track 1"
#     INDEX 01 04:17:52

function buildmetadata {
	cmd.exe /c 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe' "https://fridaynighttech.com/episodes/$name/"
	read -e -p "Starting point: " -i "100" spoint # Intro length.
	echo -e '\n[CHAPTER]\nTIMEBASE=1/1\nSTART='0'\nEND='$spoint'\ntitle='"Intro" >> "$dstpath/${name}_metadata"
	read -p "Starting line: " line # first track line number in tweets.csv
	prev=$spoint
	read -p "lines to repeat: " type # how many tracks are in the episode
	until [[ $type == 0 ]]; do
		title="$(sed "${line}q;d" $tweets)"
		echo "$title"
		echo -e "[CHAPTER]\nTIMEBASE=1/1" >> $dstpath/${name}_metadata
		cdate=$(sed "$((line))q;d" /mnt/c/Users/Ray/Desktop/tweets/tweets_formatted.csv | cut -c1-19)
		ndate=$(sed "$((line-1))q;d" /mnt/c/Users/Ray/Desktop/tweets/tweets_formatted.csv | cut -c1-19)
		diff=$(python3 /mnt/d/Users/Ray/MEGA/Scripts/FNT_tag_project/TimeDiff.py $cdate $ndate)
		end=$(($prev+diff))
		echo 'START='$prev >> $dstpath/${name}_metadata
		echo 'END='$end >> $dstpath/${name}_metadata
		echo 'title='$(echo $title | cut -c21-) >> $dstpath/${name}_metadata
		type=$(($type-1))
		prev=$end
		unset end
		line=$(($line-1))
	done
	unset done
}

tweets="/mnt/c/Users/Ray/Desktop/tweets/tweets_formatted.csv"
srcpath=/mnt/d/Users/Ray/MoreMusic/FNT
dstpath=/mnt/d/Users/Ray/MoreMusic/FNT/metadata
delete=0

# change container from mp3 to m4a
for file in $srcpath/*.mp3; do
	name=`basename $file | cut -d'.' -f1`;
	echo $name;
	ffmpeg -i "$file" -f ffmetadata "$dstpath/${name}_metadata" # extract basic metadata
	
	# process csv here
	if [[ $? != 0 ]]; then read -e -p "Skip this file? [y/n] " -i "y" skipit ; fi
	if [[ $skipit != y ]]; then echo "$name" ; buildmetadata; else skipit=n ;  fi
	read -e -p "Processing done. Modify? " -i "n" modify # we want to have an option of modification in case tweets.csv doesn't line up correctly
	if [[ "$modify" != "n" ]]; then
		modify=n
		cmd.exe /c "C:\Program Files (x86)\Notepad++\notepad++.exe" 'D:\Users\Ray\MoreMusic\FNT\metadata\'"$name"'_metadata'
		read -p "Waiting for ENTER."
	fi
done

echo "Program completed sucessfully."
exit 0
