REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "fnt-193"
PERFORMER ""
FILE "fnt-193.mp3" MP3
  TRACK 01 AUDIO
    TITLE "Intro"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Unknown Artist - Track 1"
    INDEX 01 04:17:52