REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "Ferromagnetic Failure"
PERFORMER "..::XANA::.. Creations"
FILE "fnt-185.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft6"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "The Doobie Brothers - Without You"
    INDEX 01 01:43:00
  TRACK 03 AUDIO
    TITLE "talk: Lettuce - Get Greasy"
    INDEX 01 06:47:00
  TRACK 04 AUDIO
    TITLE "The Bird and the Bee - Polite Dance Song"
    INDEX 01 11:05:00
  TRACK 05 AUDIO
    TITLE "Missio - Middle Fingers"
    INDEX 01 14:49:00
  TRACK 06 AUDIO
    TITLE "AWOLNATION - Hollow Moon (Bad Wolf)"
    INDEX 01 18:20:00
  TRACK 07 AUDIO
    TITLE "Woodkid - Run Boy Run"
    INDEX 01 22:50:00
  TRACK 08 AUDIO
    TITLE "talk: Johnny Klimek, Tom Tykwer, and Gabriel Mounsey - Sense8 OST - Too Slow"
    INDEX 01 26:07:00
  TRACK 09 AUDIO
    TITLE "Nico Vega - Beast"
    INDEX 01 29:19:00
  TRACK 10 AUDIO
    TITLE "Bad Suns - Patience"
    INDEX 01 33:20:00
  TRACK 11 AUDIO
    TITLE "Keenhouse - Deep In The Forest"
    INDEX 01 37:03:00
  TRACK 12 AUDIO
    TITLE "Justice - Fire"
    INDEX 01 42:25:00
  TRACK 13 AUDIO
    TITLE "talk: King Gizzard & The Lizard Wizard - The River"
    INDEX 01 47:53:00
  TRACK 14 AUDIO
    TITLE "Stephen - Crossfire"
    INDEX 01 54:37:00
  TRACK 15 AUDIO
    TITLE "Dead C.A.T Bounce Feat. Emily Underhill - Nothing to Say (Original Mix)"
    INDEX 01 59:05:00
  TRACK 16 AUDIO
    TITLE "Adam Freeland - Glowsticks (Original Mix)"
    INDEX 01 62:59:00
  TRACK 17 AUDIO
    TITLE "Gorillaz - Dare (Noize Generation Remix)"
    INDEX 01 68:06:00
  TRACK 18 AUDIO
    TITLE "Missill - Glitch feat. Jahcoozi (Original Mix)"
    INDEX 01 74:10:00
  TRACK 19 AUDIO
    TITLE "James Egbert - Jettison (Original Mix)"
    INDEX 01 78:47:00
  TRACK 20 AUDIO
    TITLE "talk: Adhesive Wombat - Ball Point"
    INDEX 01 83:08:00
  TRACK 21 AUDIO
    TITLE "Nora En Pure - Morning Dew (Original Mix)"
    INDEX 01 84:22:00
  TRACK 22 AUDIO
    TITLE "The Crystal Method - Born Too Slow"
    INDEX 01 86:53:00
  TRACK 23 AUDIO
    TITLE "Rage Against The Machine - Wake Up"
    INDEX 01 94:56:00
  TRACK 24 AUDIO
    TITLE "Nine Inch Nails - Capital G"
    INDEX 01 100:56:00
  TRACK 25 AUDIO
    TITLE "talk: Nine Inch Nails - 2 Ghosts I"
    INDEX 01 104:49:00
  TRACK 26 AUDIO
    TITLE "dZihan & Kamien - Bazooka"
    INDEX 01 108:03:00
  TRACK 27 AUDIO
    TITLE "FunkstÃ¶rung - Laid Out feat. Anothr"
    INDEX 01 111:08:00
  TRACK 28 AUDIO
    TITLE "Depeche Mode - Dream On"
    INDEX 01 113:16:00
  TRACK 29 AUDIO
    TITLE "London Elektricity - Point Of No Return"
    INDEX 01 117:33:00
  TRACK 30 AUDIO
    TITLE "talk: Sam Hulick - Uncharted Worlds"
    INDEX 01 123:24:00
  TRACK 31 AUDIO
    TITLE "THBD - Lost In The Night (Feat. Pipa Moran)"
    INDEX 01 125:09:00
  TRACK 32 AUDIO
    TITLE "Technimatic - Imperfections (Interlude) (Original Mix)"
    INDEX 01 129:43:00
  TRACK 33 AUDIO
    TITLE "Trevor Something - Analogue Soul"
    INDEX 01 131:33:00
  TRACK 34 AUDIO
    TITLE "The Queenstons - Hello Bed"
    INDEX 01 133:24:00
  TRACK 35 AUDIO
    TITLE "Maribou State - Tongue"
    INDEX 01 135:56:00
  TRACK 36 AUDIO
    TITLE "Jack Wall - Vigil"
    INDEX 01 141:00:00
  TRACK 37 AUDIO
    TITLE "Huma-Huma - Eureka"
    INDEX 01 142:40:00
  TRACK 38 AUDIO
    TITLE "Avari - Of The Heavens"
    INDEX 01 145:40:00
  TRACK 39 AUDIO
    TITLE "Curtis Schweitzer - light is laying waste the heavens"
    INDEX 01 149:56:00
  TRACK 40 AUDIO
    TITLE "talk: deadmau5 - Somewhere Up Here"
    INDEX 01 154:46:00
  TRACK 41 AUDIO
    TITLE "FÃ©vrier - Empress (3noneTwo Remix)"
    INDEX 01 160:24:00
  TRACK 42 AUDIO
    TITLE "Yoshihisa Hirano, Hideki Taniuchi and Various - Sinigami Kai"
    INDEX 01 166:30:00
  TRACK 43 AUDIO
    TITLE "Boom Boom Satellites - Looking Glass"
    INDEX 01 169:52:00
  TRACK 44 AUDIO
    TITLE "London Grammar - Hey Now (Bonobo Remix)"
    INDEX 01 170:50:00
  TRACK 45 AUDIO
    TITLE "Radiohead - Everything in Its Right Place"
    INDEX 01 176:36:00
  TRACK 46 AUDIO
    TITLE "Loverdose - I Remember (Original Mix)"
    INDEX 01 181:21:00
  TRACK 47 AUDIO
    TITLE "Nora En Pure - True (Original Mix)"
    INDEX 01 186:57:00
  TRACK 48 AUDIO
    TITLE "Dimitri Andreas - Run And Hide (Afrilounge remix)"
    INDEX 01 192:43:00
  TRACK 49 AUDIO
    TITLE "talk: Modest Mouse - The Air"
    INDEX 01 199:40:00
  TRACK 50 AUDIO
    TITLE "Space Vision - Go For Landing"
    INDEX 01 204:30:00
  TRACK 51 AUDIO
    TITLE "Infected Mushroom - Becoming Insane"
    INDEX 01 212:42:00
  TRACK 52 AUDIO
    TITLE "talk: Wolfgun - Lucid Bill"
    INDEX 01 220:02:00
  TRACK 53 AUDIO
    TITLE "Adhesive Wombat - Feel the Jank (extended)"
    INDEX 01 222:06:00
  TRACK 54 AUDIO
    TITLE "Course Of Empire - Infested (Darwin-Goodman Mix)"
    INDEX 01 225:30:00
  TRACK 55 AUDIO
    TITLE "Ambrosia - Time Waits For No One"
    INDEX 01 231:15:00
