REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-163 Psy Guns"
PERFORMER "..::XANA Creations::.."
FILE "fnt-163.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft4"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Studio Killers - Ode To The Bouncer"
    INDEX 01 01:27:00
  TRACK 03 AUDIO
    TITLE "talk: Karl Sav - Octoadic (Original Mix)"
    INDEX 01 05:00:00
  TRACK 04 AUDIO
    TITLE "Favored Nation - The Set Up"
    INDEX 01 10:16:00
  TRACK 05 AUDIO
    TITLE "Royal Blood - Figure It Out"
    INDEX 01 14:12:00
  TRACK 06 AUDIO
    TITLE "Rage Against The Machine - Wake Up"
    INDEX 01 17:17:00
  TRACK 07 AUDIO
    TITLE "Twenty One Pilots - Semi-Automatic"
    INDEX 01 23:16:00
  TRACK 08 AUDIO
    TITLE "Woodkid - Run Boy Run"
    INDEX 01 27:43:00
  TRACK 09 AUDIO
    TITLE "talk: Pulpalicious - The Legacy"
    INDEX 01 31:15:00
  TRACK 10 AUDIO
    TITLE "The Chemical Brothers - Snow"
    INDEX 01 35:52:00
  TRACK 11 AUDIO
    TITLE "The Chemical Brothers - Escape Velocity"
    INDEX 01 42:00:00
  TRACK 12 AUDIO
    TITLE "talk: Vortex - Doing It (Original Mix)"
    INDEX 01 52:58:00
  TRACK 13 AUDIO
    TITLE "Sub Focus - Turn Back Time (Special Request Remix)"
    INDEX 01 59:02:00
  TRACK 14 AUDIO
    TITLE "I See MONSTAS - Evolution"
    INDEX 01 64:16:00
  TRACK 15 AUDIO
    TITLE "Khurt - We Want (Original Mix)"
    INDEX 01 68:08:00
  TRACK 16 AUDIO
    TITLE "Pet Shop Boys - Sodom (TrentemÃ¸ller Mix)"
    INDEX 01 72:25:00
  TRACK 17 AUDIO
    TITLE "talk: Kodomo - Concept 15"
    INDEX 01 79:45:00
  TRACK 18 AUDIO
    TITLE "ZHU - Stay Closer"
    INDEX 01 82:26:00
  TRACK 19 AUDIO
    TITLE "OVERWORK - I Feel Better"
    INDEX 01 86:45:00
  TRACK 20 AUDIO
    TITLE "Wolfgang Gartner - Flashback (Original Mix)"
    INDEX 01 93:46:00
  TRACK 21 AUDIO
    TITLE "Yuksek - Extra Ball (The Noisy Freaks Remix)"
    INDEX 01 98:46:00
  TRACK 22 AUDIO
    TITLE "talk: BT - Last Moment of Clarity"
    INDEX 01 102:29:00
  TRACK 23 AUDIO
    TITLE "FunkstÃ¶rung - Laid Out feat. Anothr"
    INDEX 01 109:00:00
  TRACK 24 AUDIO
    TITLE "Neus - Amanita"
    INDEX 01 111:06:00
  TRACK 25 AUDIO
    TITLE "Visinin - Noneshallpass"
    INDEX 01 114:09:00
  TRACK 26 AUDIO
    TITLE "Muzzy - Feeling Stronger (feat. Charlotte Colley) (Original Mix)"
    INDEX 01 117:06:00
  TRACK 27 AUDIO
    TITLE "Death Cab For Cutie - Black Sun"
    INDEX 01 123:26:00
  TRACK 28 AUDIO
    TITLE "talk: The Dust Brothers - Marla"
    INDEX 01 128:14:00
  TRACK 29 AUDIO
    TITLE "Renzo Marini - Insane Robot"
    INDEX 01 130:27:00
  TRACK 30 AUDIO
    TITLE "Deorro - Five Hours (Donâ€™t Hold Me Back) feat. DyCy (Vocal Radio Edit)"
    INDEX 01 138:05:00
  TRACK 31 AUDIO
    TITLE "Andrew Bayer - Counting the Points"
    INDEX 01 141:50:00
  TRACK 32 AUDIO
    TITLE "BT - Love On Haight Street"
    INDEX 01 150:14:00
  TRACK 33 AUDIO
    TITLE "Nine Inch Nails - 2 Ghosts I"
    INDEX 01 156:31:00
  TRACK 34 AUDIO
    TITLE "Sordid Affair - RÃ¶yksopp"
    INDEX 01 159:46:00
  TRACK 35 AUDIO
    TITLE "Dawes - From a Window Seat"
    INDEX 01 166:45:00
  TRACK 36 AUDIO
    TITLE "Qtier - Set Me On (David August Remix)"
    INDEX 01 171:11:00
  TRACK 37 AUDIO
    TITLE "Apstract - As We Fall Silent"
    INDEX 01 178:12:00
  TRACK 38 AUDIO
    TITLE "Bobmo - Sonic Soul"
    INDEX 01 184:20:00
  TRACK 39 AUDIO
    TITLE "talk: Ulrich Schnauss - Blumenwiese Neben Autobahn"
    INDEX 01 190:00:00
  TRACK 40 AUDIO
    TITLE "Jacob, Durs - Beast"
    INDEX 01 197:55:00
  TRACK 41 AUDIO
    TITLE "RÃ¶yksopp - Thank You (Original Mix)"
    INDEX 01 204:41:00
  TRACK 42 AUDIO
    TITLE "Joey Fehrenbach - Behold"
    INDEX 01 213:42:00
