REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-183 Bedridden At A Paradise Beach Resort"
PERFORMER "..::XANA Creations::.."
FILE "fnt-183.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft6"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Alabama Shakes â€“ Sound & Color"
    INDEX 01 01:44:85
  TRACK 03 AUDIO
    TITLE "What.CD Eulogy"
    INDEX 01 01:44:85
  TRACK 04 AUDIO
    TITLE "talk: Le Matos â€“ Kiyoko"
    INDEX 01 05:06:11
  TRACK 05 AUDIO
    TITLE "Justice â€“ Helix"
    INDEX 01 10:54:36
  TRACK 06 AUDIO
    TITLE "The Correspondents â€“ Fear & Delight"
    INDEX 01 15:15:35
  TRACK 07 AUDIO
    TITLE "Favored Nations â€“ The Set Up"
    INDEX 01 18:29:80
  TRACK 08 AUDIO
    TITLE "C2C â€“ Down The Road"
    INDEX 01 22:23:58
  TRACK 09 AUDIO
    TITLE "talk: Gramatik â€“ Swucca Chust"
    INDEX 01 25:48:92
  TRACK 10 AUDIO
    TITLE "Black Strobe â€“ Boogie In Zero Gravity (Radio Edit)'"
    INDEX 01 31:15:59
  TRACK 11 AUDIO
    TITLE "The Crystal Method â€“ Name Of The Game"
    INDEX 01 34:42:45
  TRACK 12 AUDIO
    TITLE "Basement Jaxx â€“ Red Alert"
    INDEX 01 38:59:78
  TRACK 13 AUDIO
    TITLE "Tegan And Sara â€“ Closer"
    INDEX 01 43:24:05
  TRACK 14 AUDIO
    TITLE "talk: Feed Me â€“ Dazed"
    INDEX 01 46:53:10
  TRACK 15 AUDIO
    TITLE "Bleachers â€“ Rollercoaster"
    INDEX 01 52:26:74
  TRACK 16 AUDIO
    TITLE "Boom Boom Satellites â€“ All In A Day"
    INDEX 01 55:43:77
  TRACK 17 AUDIO
    TITLE "Underground, Boston â€“ Life Is feat. Vanity Jay (Original Mix)"
    INDEX 01 62:42:98
  TRACK 18 AUDIO
    TITLE "Ross D â€“ I Need You"
    INDEX 01 68:01:27
  TRACK 19 AUDIO
    TITLE "Wolfgun â€“ Road to Jupiter"
    INDEX 01 74:48:67
  TRACK 20 AUDIO
    TITLE "I See MONSTAS â€“ Evolution"
    INDEX 01 80:31:70
  TRACK 21 AUDIO
    TITLE "talk: Stephan Bodzin â€“ Sonnenwind"
    INDEX 01 84:28:34
  TRACK 22 AUDIO
    TITLE "Black Coast â€“ Trndsttr (Lucian Remix) [feat. M. Maggie]"
    INDEX 01 91:39:47
  TRACK 23 AUDIO
    TITLE "Neus â€“ Naka O Akan (J.A.C.K Remix)"
    INDEX 01 94:38:48
  TRACK 24 AUDIO
    TITLE "Muse â€“ Dead Inside (Moosak Remix)"
    INDEX 01 98:40:43
  TRACK 25 AUDIO
    TITLE "Mord Fustang â€“ Milky Way (Original Mix)"
    INDEX 01 101:35:10
  TRACK 26 AUDIO
    TITLE "Koven â€“ Breathing Me In (Original Mix)"
    INDEX 01 107:15:50
  TRACK 27 AUDIO
    TITLE "Notaker â€“ Gems"
    INDEX 01 111:41:05
  TRACK 28 AUDIO
    TITLE "talk: wrath â€“ progressive bullshit"
    INDEX 01 116:40:98
  TRACK 29 AUDIO
    TITLE "deadmau5, Grabbitz â€“ Let Go (Original Mix)"
    INDEX 01 123:36:74
  TRACK 30 AUDIO
    TITLE "Hybrid â€“ Break My Soul (Original Mix)"
    INDEX 01 129:51:82
  TRACK 31 AUDIO
    TITLE "Rudimental â€“ Powerless (feat. Becky Hill)"
    INDEX 01 137:40:56
  TRACK 32 AUDIO
    TITLE "Direct, Mr FijiWiji & Holly Drummond â€“ Trust In Me"
    INDEX 01 141:25:42
  TRACK 33 AUDIO
    TITLE "talk: Zammuto â€“ Donâ€™t Be A Tool"
    INDEX 01 145:54:78
  TRACK 34 AUDIO
    TITLE "Nigel Good feat Sarah Clark â€“ Always Running (Original Mix)"
    INDEX 01 151:18:79
  TRACK 35 AUDIO
    TITLE "Ochre â€“ Neoretro"
    INDEX 01 158:03:59
  TRACK 36 AUDIO
    TITLE "Frozen OST â€“ Reindeer(s) Are Better Than People"
    INDEX 01 163:05:16
  TRACK 37 AUDIO
    TITLE "BOOM BOOM SATELLITES â€“ Porcupine"
    INDEX 01 163:51:46
  TRACK 38 AUDIO
    TITLE "talk: Sega â€“ Sonic Mega Collection Plus Game Selection Menu"
    INDEX 01 166:13:02
  TRACK 39 AUDIO
    TITLE "Koda & Bijou â€“ There"
    INDEX 01 170:08:28
  TRACK 40 AUDIO
    TITLE "Peace Orchestra â€“ Double Drums"
    INDEX 01 173:35:64
  TRACK 41 AUDIO
    TITLE "Max Sedgley â€“ Slowly [v Z-Star]"
    INDEX 01 183:02:85
  TRACK 42 AUDIO
    TITLE "BOOM BOOM SATELLITES â€“ 40-Forty"
    INDEX 01 188:22:15
  TRACK 43 AUDIO
    TITLE "talk: Ochre â€“ Glassmaker"
    INDEX 01 194:22:55
  TRACK 44 AUDIO
    TITLE "Jon Gomm â€“ Passionflower"
    INDEX 01 200:26:40
  TRACK 45 AUDIO
    TITLE "Peace Orchestra â€“ Who Am I? (Animatrix Edit)"
    INDEX 01 207:21:62
  TRACK 46 AUDIO
    TITLE "Jose James â€“ Work Song"
    INDEX 01 213:20:32
  TRACK 47 AUDIO
    TITLE "talk: Apstract â€“ As We Fall Silent"
    INDEX 01 216:57:42
  TRACK 48 AUDIO
    TITLE "Jerome Isma-Ae, Alastor â€“ Tiger (Extended Mix)"
    INDEX 01 225:44:26
  TRACK 49 AUDIO
    TITLE "Redondo, Bolier, She Keeps Bees â€“ Every Single Piece feat. She Keeps Bees (Original Mix)"
    INDEX 01 232:56:83
  TRACK 50 AUDIO
    TITLE "The Avener â€“ Fade Out Lines (Original Mix)"
    INDEX 01 236:55:81
