REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-192 Kbps"
PERFORMER "..::XANA Creations::.."
FILE "fnt-192.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft6"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "BOOM BOOM SATELLITES â€“ Loaded"
    INDEX 01 01:39:36
  TRACK 03 AUDIO
    TITLE "talk: Le Matos â€“ Kiyoko"
    INDEX 01 07:13:04
  TRACK 04 AUDIO
    TITLE "Justice â€“ New Lands"
    INDEX 01 11:24:77
  TRACK 05 AUDIO
    TITLE "Studio Killers â€“ Ode To The Bouncer"
    INDEX 01 15:43:51
  TRACK 06 AUDIO
    TITLE "Professor Kliq â€“ Museum (Fakeout Funk)"
    INDEX 01 19:10:06
  TRACK 07 AUDIO
    TITLE "SIAMES â€“ The Wolf"
    INDEX 01 24:35:46
  TRACK 08 AUDIO
    TITLE "Hilltop Hoods â€“ 1955 (feat. Montaigne & Tom Thum)"
    INDEX 01 27:45:80
  TRACK 09 AUDIO
    TITLE "ODESZA â€“ Line Of Sight (feat. WYNNE & Mansionair)"
    INDEX 01 31:40:08
  TRACK 10 AUDIO
    TITLE "talk: Jeremy Blake â€“ Hedlok (Original Mix)"
    INDEX 01 35:44:32
  TRACK 11 AUDIO
    TITLE "Staunch â€“ My Name Isâ€¦ (Original Mix)"
    INDEX 01 40:46:42
  TRACK 12 AUDIO
    TITLE "Notaker â€“ So Much Love"
    INDEX 01 46:11:99
  TRACK 13 AUDIO
    TITLE "HI-LO â€“ Men On Mars (Extended Mix)"
    INDEX 01 52:53:02
  TRACK 14 AUDIO
    TITLE "Badjokes â€“ The Fonk (Original Mix)"
    INDEX 01 57:55:32
  TRACK 15 AUDIO
    TITLE "Slyde â€“ Frequency (NAPT Remix)"
    INDEX 01 61:11:65
  TRACK 16 AUDIO
    TITLE "twoloud â€“ Move (Showtek Edit)"
    INDEX 01 68:09:16
  TRACK 17 AUDIO
    TITLE "Muzzy, Koven & Feint â€“ Worth The Lie"
    INDEX 01 72:28:38
  TRACK 18 AUDIO
    TITLE "talk: HALLEY LABS R&D â€“ 2014-06-17 â€“ dr"
    INDEX 01 77:31:65
  TRACK 19 AUDIO
    TITLE "talk: Tim Carleton & Darrick Deel â€“ Opus No. 1"
    INDEX 01 80:26:38
  TRACK 20 AUDIO
    TITLE "Break, Kyo â€“ Give In to Me (Original Mix)"
    INDEX 01 85:10:37
  TRACK 21 AUDIO
    TITLE "Rchetype Feat. Wolfgun â€“ Voyager.RT"
    INDEX 01 90:37:44
  TRACK 22 AUDIO
    TITLE "Pendulum â€“ Out Here"
    INDEX 01 95:59:10
  TRACK 23 AUDIO
    TITLE "Karma Fields â€“ For Me (Original Mix)"
    INDEX 01 102:01:54
  TRACK 24 AUDIO
    TITLE "TrentemÃ¸ller â€“ Moan (TrentemÃ¸ller Remix)"
    INDEX 01 105:38:95
  TRACK 25 AUDIO
    TITLE "talk: The Dead Texan â€“ La Ballade dâ€™Alain Georges"
    INDEX 01 113:53:46
  TRACK 26 AUDIO
    TITLE "Jessi Teich â€“ Dark Thoughts"
    INDEX 01 120:20:15
  TRACK 27 AUDIO
    TITLE "Pirate Jams â€“ I Want You (Original Mix)"
    INDEX 01 123:39:88
  TRACK 28 AUDIO
    TITLE "ODESZA â€“ Across The Room (feat. Leon Bridges)"
    INDEX 01 128:21:67
  TRACK 29 AUDIO
    TITLE "TeZATalks â€“ Love ft. Kody Ryan (Acoustic)"
    INDEX 01 133:04:09
  TRACK 30 AUDIO
    TITLE "Casey LaLonde â€“ New Cities"
    INDEX 01 136:37:41
  TRACK 31 AUDIO
    TITLE "Christophe Heral â€“ Home sweet home"
    INDEX 01 141:18:35
  TRACK 32 AUDIO
    TITLE "talk: Fox Stevenson â€“ Essby (6 Months and Counting)"
    INDEX 01 144:09:58
  TRACK 33 AUDIO
    TITLE "Ochre â€“ Neoretro"
    INDEX 01 149:28:53
  TRACK 34 AUDIO
    TITLE "Nicolas Masseyeff â€“ Yianu"
    INDEX 01 154:31:90
  TRACK 35 AUDIO
    TITLE "Ugo Lucchese â€“ Inside (Andrea Bertolini Remix)"
    INDEX 01 161:36:68
  TRACK 36 AUDIO
    TITLE "Stephan Bodzin â€“ Papillon (Original Mix)"
    INDEX 01 164:41:08
  TRACK 37 AUDIO
    TITLE "Nicolas Masseyeff â€“ Mugen (Original Mix)"
    INDEX 01 171:32:87
  TRACK 38 AUDIO
    TITLE "Jobe â€“ Orcus (Original Mix)"
    INDEX 01 175:59:47
  TRACK 39 AUDIO
    TITLE "Bobmo â€“ Sonic Soul"
    INDEX 01 184:52:26
  TRACK 40 AUDIO
    TITLE "COLONEL RED â€“ Wake"
    INDEX 01 191:01:55
