REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-190 Anime Lo-Fi Aesthetic"
PERFORMER "..::XANA Creations::.."
FILE "fnt-190.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft6"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Robert DeLong â€“ Long Way Down"
    INDEX 01 01:42:33
  TRACK 03 AUDIO
    TITLE "talk: AllttA â€“ AllttA (Instrumental)"
    INDEX 01 05:33:35
  TRACK 04 AUDIO
    TITLE "The Crystal Method â€“ High Roller"
    INDEX 01 08:59:67
  TRACK 05 AUDIO
    TITLE "NoMBe â€“ Do Whatchu Want To Me"
    INDEX 01 13:01:49
  TRACK 06 AUDIO
    TITLE "Bel Heir â€“ Kiss the Devil"
    INDEX 01 16:21:80
  TRACK 07 AUDIO
    TITLE "Holy Fuck â€“ Tom Tom"
    INDEX 01 19:28:19
  TRACK 08 AUDIO
    TITLE "talk: Criterion Games & Acclaim Entertainment â€“ Burnout Main Menu"
    INDEX 01 23:17:57
  TRACK 09 AUDIO
    TITLE "Wolfgun â€“ Extol"
    INDEX 01 27:26:11
  TRACK 10 AUDIO
    TITLE "Baba Brinkman â€“ Spread It"
    INDEX 01 31:29:80
  TRACK 11 AUDIO
    TITLE "Boom Boom Satellites â€“ What Goes Round Comes Around"
    INDEX 01 34:21:86
  TRACK 12 AUDIO
    TITLE "CRX â€“ Broken Bones"
    INDEX 01 38:50:18
  TRACK 13 AUDIO
    TITLE "Brett Domino â€“ Bad Bad Boy"
    INDEX 01 42:51:57
  TRACK 14 AUDIO
    TITLE "Swing Republic â€“ Not Alone"
    INDEX 01 46:31:10
  TRACK 15 AUDIO
    TITLE "Unlike Pluto â€“ Let It Bleed (feat. Cristina Gatti)"
    INDEX 01 49:32:97
  TRACK 16 AUDIO
    TITLE "Koven & Crystal Skies â€“ You Me And Gravity"
    INDEX 01 52:52:08
  TRACK 17 AUDIO
    TITLE "Far Out â€“ New Beginning"
    INDEX 01 56:41:66
  TRACK 18 AUDIO
    TITLE "talk: Bill Brown â€“ Tour Intro Windows XP OS"
    INDEX 01 60:40:41
  TRACK 19 AUDIO
    TITLE "talk: Bill Brown â€“ Tour6Bed Windows XP OS"
    INDEX 01 61:24:97
  TRACK 20 AUDIO
    TITLE "Robotaki â€“ Automaton"
    INDEX 01 64:49:36
  TRACK 21 AUDIO
    TITLE "Seven Lions & Jason Ross â€“ Higher Love feat. Paul Meany (Original Mix)"
    INDEX 01 68:27:19
  TRACK 22 AUDIO
    TITLE "Above & Beyond, Marty Longstaff â€“ Tightrope feat. Marty Longstaff (Above & Beyond Club Mix)"
    INDEX 01 73:29:34
  TRACK 23 AUDIO
    TITLE "Fox Stevenson â€“ Arigatou (Extended Mix)"
    INDEX 01 79:36:36
  TRACK 24 AUDIO
    TITLE "Nytron, Andrey Exx â€“ Shine on Me (Original Mix)"
    INDEX 01 82:00:36
  TRACK 25 AUDIO
    TITLE "James Gruntz, Pablo Nouvelle â€“ Hold On feat. James Gruntz (rrotik Extended Remix)"
    INDEX 01 87:05:50
  TRACK 26 AUDIO
    TITLE "Luttrell â€“ Daylight (Original Mix)"
    INDEX 01 91:10:90
  TRACK 27 AUDIO
    TITLE "talk: Trentemoller â€“ Liquid Dreams"
    INDEX 01 98:37:31
  TRACK 28 AUDIO
    TITLE "she â€“ Day 8"
    INDEX 01 106:23:57
  TRACK 29 AUDIO
    TITLE "Rchetype â€“ Age of Progress"
    INDEX 01 108:38:10
  TRACK 30 AUDIO
    TITLE "Boston â€“ Panoramic (Original Mix)"
    INDEX 01 112:56:33
  TRACK 31 AUDIO
    TITLE "Mystic State, Elias, Third Degree â€“ Mystic State â€“ Viewpoint (feat. Lucy Kitchen)"
    INDEX 01 118:26:47
  TRACK 32 AUDIO
    TITLE "Freeland â€“ Nowism"
    INDEX 01 124:17:01
  TRACK 33 AUDIO
    TITLE "COLONEL RED â€“ THIS LIVING"
    INDEX 01 129:25:25
  TRACK 34 AUDIO
    TITLE "Phil Collins â€“ Take Me Home"
    INDEX 01 134:33:74
  TRACK 35 AUDIO
    TITLE "Zammuto â€“ My Dogâ€™s Eyes"
    INDEX 01 142:34:66
  TRACK 36 AUDIO
    TITLE "Avari â€“ Of The Heavens"
    INDEX 01 145:33:89
  TRACK 37 AUDIO
    TITLE "Wild Beasts â€“ Big Cat"
    INDEX 01 149:56:58
  TRACK 38 AUDIO
    TITLE "Darkside â€“ Heart"
    INDEX 01 153:01:01
  TRACK 39 AUDIO
    TITLE "Darkside â€“ Paper Trails"
    INDEX 01 157:11:89
  TRACK 40 AUDIO
    TITLE "D*Note â€“ Sylvia"
    INDEX 01 161:53:87
  TRACK 41 AUDIO
    TITLE "Doug Hammer â€“ glorious"
    INDEX 01 166:19:75
  TRACK 42 AUDIO
    TITLE "talk: Tom Tykwer & Johnny Klimek â€“ Tick Tock"
    INDEX 01 169:40:03
  TRACK 43 AUDIO
    TITLE "Khruangbin â€“ The Number 4"
    INDEX 01 173:21:67
  TRACK 44 AUDIO
    TITLE "jinsang â€“ untold"
    INDEX 01 176:59:80
  TRACK 45 AUDIO
    TITLE "Phone Cameras"
    INDEX 01 178:34:82
  TRACK 46 AUDIO
    TITLE ""New Age Bitch""
    INDEX 01 179:41:06
  TRACK 47 AUDIO
    TITLE ""New Age Fuccboi""
    INDEX 01 179:51:74
  TRACK 48 AUDIO
    TITLE ""Fuccthey""
    INDEX 01 180:08:40
  TRACK 49 AUDIO
    TITLE "idealism â€“ a moment of silence"
    INDEX 01 180:20:00
  TRACK 50 AUDIO
    TITLE "Don Henley â€“ Sunset Grill"
    INDEX 01 182:29:92
