REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-100 Friday Night Tech"
PERFORMER "..::XANA::.. Creations"
FILE "fnt-100.mp3" MP3
  TRACK 01 AUDIO
    TITLE "Chase & Status - Blind Faith"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "talk: Wolfgun - Twilight Castle"
    INDEX 01 03:53:62
  TRACK 03 AUDIO
    TITLE "The Eagles - Life In The Fast Lane"
    INDEX 01 06:53:24
  TRACK 04 AUDIO
    TITLE "Nazareth - Hair of the Dog"
    INDEX 01 12:04:79
  TRACK 05 AUDIO
    TITLE "Robert Randolph & the Family Band - Ain't Nothing Wrong With That"
    INDEX 01 16:06:90
  TRACK 06 AUDIO
    TITLE "Five Man Electrical Banc - I'm A Stranger Here (LP Version)"
    INDEX 01 19:29:72
  TRACK 07 AUDIO
    TITLE "talk: Tinush - Man At Work (soundcloud rip)"
    INDEX 01 23:08:66
  TRACK 08 AUDIO
    TITLE "The White Stripes - Seven Nation Army"
    INDEX 01 30:16:47
  TRACK 09 AUDIO
    TITLE "RJD2 - Ghostwriter"
    INDEX 01 34:04:88
  TRACK 10 AUDIO
    TITLE "Shiny Toy Guns - Le Disko"
    INDEX 01 39:18:50
  TRACK 11 AUDIO
    TITLE "talk: Stephan Bodzin - Sonnen Wind"
    INDEX 01 42:38:28
  TRACK 12 AUDIO
    TITLE "Daft Punk - The Grid (The Crystal Method Remix)"
    INDEX 01 50:07:02
  TRACK 13 AUDIO
    TITLE "The Prodigy - Omen (Noisia Remix)"
    INDEX 01 54:30:81
  TRACK 14 AUDIO
    TITLE "talk: Pronobozo - Java"
    INDEX 01 60:42:93
  TRACK 15 AUDIO
    TITLE "Amen Andrews - London"
    INDEX 01 64:59:23
  TRACK 16 AUDIO
    TITLE "London Music Works & Clint Mansell - Requiem for a Tower"
    INDEX 01 69:00:72
  TRACK 17 AUDIO
    TITLE "Nero - Syndicate (Nero Remix)"
    INDEX 01 72:55:03
  TRACK 18 AUDIO
    TITLE "London Elektricity - Sat Nav"
    INDEX 01 76:42:83
  TRACK 19 AUDIO
    TITLE "talk: Haito & Diringer - Perception"
    INDEX 01 83:34:88
  TRACK 20 AUDIO
    TITLE "NERVO ft. Steve Aoki & Afrojack - We're All No One (The Noisy Freaks Remix) (soundcloud rip)"
    INDEX 01 93:10:95
  TRACK 21 AUDIO
    TITLE "Pointer Sisters - Automatic (SNDCLSH & DJ Kue Remix)"
    INDEX 01 97:08:63
  TRACK 22 AUDIO
    TITLE "Probe - Ultimate (Original Mix) (CahulHouseMafia.Net)"
    INDEX 01 102:01:07
  TRACK 23 AUDIO
    TITLE "Madeon - Icarus (Original Mix)"
    INDEX 01 107:28:41
  TRACK 24 AUDIO
    TITLE "fRew - Under The Sun [Lazy Rich Remix] *Dan Veytia Edit*"
    INDEX 01 113:27:63
  TRACK 25 AUDIO
    TITLE "Savant - Alphas 2012"
    INDEX 01 119:13:81
  TRACK 26 AUDIO
    TITLE "Porter Robinson - Spitfire (Save The Rave Re-Fix)"
    INDEX 01 124:37:23
  TRACK 27 AUDIO
    TITLE "talk: The Dead Texan - La Ballade d'Alain Georges"
    INDEX 01 131:40:03
  TRACK 28 AUDIO
    TITLE "Shiny Toy Guns - It Became A Lie On You"
    INDEX 01 137:55:73
  TRACK 29 AUDIO
    TITLE "Schiller - Dream of You"
    INDEX 01 142:18:89
  TRACK 30 AUDIO
    TITLE "Pendulum - The Tempest"
    INDEX 01 146:24:53
  TRACK 31 AUDIO
    TITLE "talk: Textural Being - Fractal Beach"
    INDEX 01 153:50:52
  TRACK 32 AUDIO
    TITLE "JULIAN SMITH - Techno Jeep"
    INDEX 01 160:54:15
  TRACK 33 AUDIO
    TITLE "Sub Focus - Out The Blue ft. Alice Gold"
    INDEX 01 162:45:25
  TRACK 34 AUDIO
    TITLE "Matrix & Chords - Hypnotize"
    INDEX 01 166:32:47
  TRACK 35 AUDIO
    TITLE "Bcee - Captured In Time (Chris S.U Remix)"
    INDEX 01 171:27:27
  TRACK 36 AUDIO
    TITLE "Colossus - Under the Weather"
    INDEX 01 178:49:02
  TRACK 37 AUDIO
    TITLE "Majik & Wickaman - Crazy World (Extended Radio Edit)"
    INDEX 01 185:57:60
  TRACK 38 AUDIO
    TITLE "Pendulum - Fasten Your Seatbelt (PrototypeRaptor Bootleg Remix)"
    INDEX 01 191:39:76
  TRACK 39 AUDIO
    TITLE "Pendulum - Set Me On Fire"
    INDEX 01 197:46:88
  TRACK 40 AUDIO
    TITLE "RackNRuin feat Janai - Dazed & Confused (SKisM's Baroque Out Remix)"
    INDEX 01 202:59:12
  TRACK 41 AUDIO
    TITLE "talk: Sage Taylor - Firewalk"
    INDEX 01 207:47:82
  TRACK 42 AUDIO
    TITLE "Dan Veytia - In And Out Of Phase / Take Me Under Your Skin [Andrew Bayer and Matt Lange vs. TrentemÃ¸ller]"
    INDEX 01 214:00:10
  TRACK 43 AUDIO
    TITLE "talk: Gui Boratto - Tales From The Lab (Part 2)"
    INDEX 01 224:55:87
  TRACK 44 AUDIO
    TITLE "Trevor Gordon Hall - Pine Tree and Power Lines"
    INDEX 01 232:00:09
  TRACK 45 AUDIO
    TITLE "3noneTwo & Win and Tonic (Dwell) - 100228 (Magic Collaboration)"
    INDEX 01 244:59:00
