REM GENRE Podcast
REM COMMENT "This cue file has been generated by Manual, @CatVsHumanity on Twitter. No rights reserved."
TITLE "FNT-187 Psydchain Compressor"
PERFORMER "..::XANA Creations::.."
FILE "fnt-187.mp3" MP3
  TRACK 01 AUDIO
    TITLE "fnt-s7-intro-draft6"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Freeland â€“ Under Control"
    INDEX 01 01:42:72
  TRACK 03 AUDIO
    TITLE "talk: Lettuce â€“ Get Greasy"
    INDEX 01 05:43:85
  TRACK 04 AUDIO
    TITLE "alt-J â€“ Left Hand Free (Extended Version)"
    INDEX 01 10:11:86
  TRACK 05 AUDIO
    TITLE "C2C Feat Kentaro And Netik And Rafik And Tigerstyle And Vajra â€“ Le Banquet"
    INDEX 01 13:01:65
  TRACK 06 AUDIO
    TITLE "Zedd â€“ Candyman"
    INDEX 01 17:54:31
  TRACK 07 AUDIO
    TITLE "Smuffy â€“ Sly Bunny"
    INDEX 01 20:58:85
  TRACK 08 AUDIO
    TITLE "talk: Township Rebellion â€“ Liquid Green (Original Mix)"
    INDEX 01 24:29:49
  TRACK 09 AUDIO
    TITLE "Jungle â€“ Busy Earninâ€™"
    INDEX 01 32:09:41
  TRACK 10 AUDIO
    TITLE "Baths â€“ Indoorsy"
    INDEX 01 35:32:37
  TRACK 11 AUDIO
    TITLE "Tykwer & Klimek & Heil â€“ Running Two"
    INDEX 01 38:22:54
  TRACK 12 AUDIO
    TITLE "Spundose â€“ Alien is Familiar (Original Mix)"
    INDEX 01 42:34:79
  TRACK 13 AUDIO
    TITLE "Broken Eye â€“ Retro Skank (Original Mix)"
    INDEX 01 47:46:88
  TRACK 14 AUDIO
    TITLE "Max Sedgley â€“ Whatâ€™ve I Got To Do? (Original Mix)"
    INDEX 01 52:32:18
  TRACK 15 AUDIO
    TITLE "Igorrr & Ruby My Dear â€“ Barbecue"
    INDEX 01 58:01:76
  TRACK 16 AUDIO
    TITLE "MYRNE â€“ Afterdark (feat. Aviella)"
    INDEX 01 62:01:29
  TRACK 17 AUDIO
    TITLE "talk: Thomas Vent â€“ Grace (Original Mix)"
    INDEX 01 65:21:68
  TRACK 18 AUDIO
    TITLE "Boom Boom Satellites â€“ Back On My Feet (Live at Sweet Love Shower 2010)"
    INDEX 01 72:30:36
  TRACK 19 AUDIO
    TITLE "Boom Boom Satellites â€“ Kick It Out (Live at Sweet Love Shower 2010)"
    INDEX 01 80:35:00
  TRACK 20 AUDIO
    TITLE "30Hz â€“ Daddio (Miles Dyson Remix)"
    INDEX 01 87:10:43
  TRACK 21 AUDIO
    TITLE "Ariana Grande â€“ Into You (3LAU Remix)"
    INDEX 01 93:24:93
  TRACK 22 AUDIO
    TITLE "talk: Don Davis â€“ The Hotel Ambush"
    INDEX 01 96:41:16
  TRACK 23 AUDIO
    TITLE "Tears For Fears â€“ Shout (Wrathâ€™s Grum Edit)"
    INDEX 01 102:46:74
  TRACK 24 AUDIO
    TITLE "Queensryche â€“ Operation: Mindcrime"
    INDEX 01 107:21:65
  TRACK 25 AUDIO
    TITLE "J.A.C.K â€“ M a g e l l a n"
    INDEX 01 112:06:39
  TRACK 26 AUDIO
    TITLE "talk: Lincoln Grounds & Randall Breneman â€“ Death Row"
    INDEX 01 116:48:99
  TRACK 27 AUDIO
    TITLE "Throttle â€“ Money Maker (Club Mix)"
    INDEX 01 120:46:40
  TRACK 28 AUDIO
    TITLE "Yotto â€“ Aviate"
    INDEX 01 124:09:19
  TRACK 29 AUDIO
    TITLE "RÃœFÃœS â€“ Like An Animal (Yotto Remix)"
    INDEX 01 129:59:81
  TRACK 30 AUDIO
    TITLE "Yotto â€“ Crosswalk"
    INDEX 01 135:12:68
  TRACK 31 AUDIO
    TITLE "talk: Modest Mouse â€“ The Air"
    INDEX 01 143:24:02
  TRACK 32 AUDIO
    TITLE "Liquid Soul, Zyce, Solar Kid â€“ We Come In Peace (Talpa Remix)"
    INDEX 01 147:12:80
  TRACK 33 AUDIO
    TITLE "Bitmonx, Fabio â€“ Erdbeer Kiwi (Captain Hook & DJ Wasabi Remix)"
    INDEX 01 152:59:72
  TRACK 34 AUDIO
    TITLE "Cornelius Jones â€“ Floored (ft. 3noneTwo)"
    INDEX 01 161:47:22
  TRACK 35 AUDIO
    TITLE "Johnny â€˜Guitarâ€™ Watson â€“ A Real Mother For Ya"
    INDEX 01 166:02:27
  TRACK 36 AUDIO
    TITLE "Koda â€“ Staying"
    INDEX 01 170:56:54
  TRACK 37 AUDIO
    TITLE "talk: Ludovico Einaudi â€“ Twice"
    INDEX 01 175:12:67
  TRACK 38 AUDIO
    TITLE "UNKLE â€“ The Answer (TrentemÃ¸ller Remix) (feat. Big in Japan (Baltimore))"
    INDEX 01 179:50:96
